"""create jwt tokens table

Revision ID: 8f68664a794f
Revises: 5a36b2f48c9c
Create Date: 2025-07-28 16:19:19.972443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f68664a794f'
down_revision: Union[str, Sequence[str], None] = '5a36b2f48c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'jwt_tokens',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('access_token', sa.String(length=1000), nullable=False),
        sa.Column('refresh_token', sa.String(length=1000), nullable=False),
        sa.Column('access_token_expired_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('refresh_token_expired_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_dt', sa.DateTime(timezone=True), nullable=True),
    )
    
    # Добавляем внешний ключ
    op.create_foreign_key('fk_jwt_tokens_user_id', 'jwt_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_jwt_tokens_user_id', 'jwt_tokens', type_='foreignkey')
    op.drop_table('jwt_tokens')
    # ### end Alembic commands ###
